export const BREAKİNG_BAD_QUOTE = "BREAKİNG_BAD_QUOTE";
export const BREAKİNG_BAD_CHARACTER = "BREAKİNG_BAD_CHARACTER";
export const BETTER_CAUL_SAUL_QUOTE = "BETTER_CAUL_SAUL_QUOTE";
export const BETTER_CAUL_SAUL_CHARACTER = "BETTER_CAUL_SAUL_CHARACTER";
